apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: spring-petclinic
  labels:
    environment: production
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: springio/petclinic:latest
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: spring-petclinic
